version: "3.7"

services:
  mongodb:
    image: "mongo:${MONGODB_VERSION}"
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - ./events.js:/docker-entrypoint-initdb.d/events.js
    container_name: events-mongodb
  mongo_seed:
    build: mongo-seed/.
    links:
      - mongodb
volumes:
  mongodb: